// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

package com.ikea.bigdata.protos;

public final class OrderProtos {
    private OrderProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface OrderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.ikea.bigdata.protos.Order)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string modelNumber = 1;</code>
         */
        java.lang.String getModelNumber();
        /**
         * <code>string modelNumber = 1;</code>
         */
        com.google.protobuf.ByteString
        getModelNumberBytes();

        /**
         * <code>int32 cost = 2;</code>
         */
        int getCost();

        /**
         * <code>string email = 3;</code>
         */
        java.lang.String getEmail();
        /**
         * <code>string email = 3;</code>
         */
        com.google.protobuf.ByteString
        getEmailBytes();

        /**
         * <code>string shippingAddress = 4;</code>
         */
        java.lang.String getShippingAddress();
        /**
         * <code>string shippingAddress = 4;</code>
         */
        com.google.protobuf.ByteString
        getShippingAddressBytes();

        /**
         * <code>string mobileNumber = 5;</code>
         */
        java.lang.String getMobileNumber();
        /**
         * <code>string mobileNumber = 5;</code>
         */
        com.google.protobuf.ByteString
        getMobileNumberBytes();
    }
    /**
     * Protobuf type {@code com.ikea.bigdata.protos.Order}
     */
    public  static final class Order extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.ikea.bigdata.protos.Order)
            OrderOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Order.newBuilder() to construct.
        private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Order() {
            modelNumber_ = "";
            cost_ = 0;
            email_ = "";
            shippingAddress_ = "";
            mobileNumber_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Order(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            modelNumber_ = s;
                            break;
                        }
                        case 16: {

                            cost_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            email_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            shippingAddress_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            mobileNumber_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.ikea.bigdata.protos.OrderProtos.internal_static_com_ikea_bigdata_protos_Order_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.ikea.bigdata.protos.OrderProtos.internal_static_com_ikea_bigdata_protos_Order_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.ikea.bigdata.protos.OrderProtos.Order.class, com.ikea.bigdata.protos.OrderProtos.Order.Builder.class);
        }

        public static final int MODELNUMBER_FIELD_NUMBER = 1;
        private volatile java.lang.Object modelNumber_;
        /**
         * <code>string modelNumber = 1;</code>
         */
        public java.lang.String getModelNumber() {
            java.lang.Object ref = modelNumber_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                modelNumber_ = s;
                return s;
            }
        }
        /**
         * <code>string modelNumber = 1;</code>
         */
        public com.google.protobuf.ByteString
        getModelNumberBytes() {
            java.lang.Object ref = modelNumber_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                modelNumber_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COST_FIELD_NUMBER = 2;
        private int cost_;
        /**
         * <code>int32 cost = 2;</code>
         */
        public int getCost() {
            return cost_;
        }

        public static final int EMAIL_FIELD_NUMBER = 3;
        private volatile java.lang.Object email_;
        /**
         * <code>string email = 3;</code>
         */
        public java.lang.String getEmail() {
            java.lang.Object ref = email_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                email_ = s;
                return s;
            }
        }
        /**
         * <code>string email = 3;</code>
         */
        public com.google.protobuf.ByteString
        getEmailBytes() {
            java.lang.Object ref = email_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SHIPPINGADDRESS_FIELD_NUMBER = 4;
        private volatile java.lang.Object shippingAddress_;
        /**
         * <code>string shippingAddress = 4;</code>
         */
        public java.lang.String getShippingAddress() {
            java.lang.Object ref = shippingAddress_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                shippingAddress_ = s;
                return s;
            }
        }
        /**
         * <code>string shippingAddress = 4;</code>
         */
        public com.google.protobuf.ByteString
        getShippingAddressBytes() {
            java.lang.Object ref = shippingAddress_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                shippingAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MOBILENUMBER_FIELD_NUMBER = 5;
        private volatile java.lang.Object mobileNumber_;
        /**
         * <code>string mobileNumber = 5;</code>
         */
        public java.lang.String getMobileNumber() {
            java.lang.Object ref = mobileNumber_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                mobileNumber_ = s;
                return s;
            }
        }
        /**
         * <code>string mobileNumber = 5;</code>
         */
        public com.google.protobuf.ByteString
        getMobileNumberBytes() {
            java.lang.Object ref = mobileNumber_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                mobileNumber_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getModelNumberBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modelNumber_);
            }
            if (cost_ != 0) {
                output.writeInt32(2, cost_);
            }
            if (!getEmailBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
            }
            if (!getShippingAddressBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shippingAddress_);
            }
            if (!getMobileNumberBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mobileNumber_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getModelNumberBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modelNumber_);
            }
            if (cost_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, cost_);
            }
            if (!getEmailBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
            }
            if (!getShippingAddressBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shippingAddress_);
            }
            if (!getMobileNumberBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mobileNumber_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.ikea.bigdata.protos.OrderProtos.Order)) {
                return super.equals(obj);
            }
            com.ikea.bigdata.protos.OrderProtos.Order other = (com.ikea.bigdata.protos.OrderProtos.Order) obj;

            boolean result = true;
            result = result && getModelNumber()
                    .equals(other.getModelNumber());
            result = result && (getCost()
                    == other.getCost());
            result = result && getEmail()
                    .equals(other.getEmail());
            result = result && getShippingAddress()
                    .equals(other.getShippingAddress());
            result = result && getMobileNumber()
                    .equals(other.getMobileNumber());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MODELNUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getModelNumber().hashCode();
            hash = (37 * hash) + COST_FIELD_NUMBER;
            hash = (53 * hash) + getCost();
            hash = (37 * hash) + EMAIL_FIELD_NUMBER;
            hash = (53 * hash) + getEmail().hashCode();
            hash = (37 * hash) + SHIPPINGADDRESS_FIELD_NUMBER;
            hash = (53 * hash) + getShippingAddress().hashCode();
            hash = (37 * hash) + MOBILENUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getMobileNumber().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.ikea.bigdata.protos.OrderProtos.Order parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.ikea.bigdata.protos.OrderProtos.Order prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.ikea.bigdata.protos.Order}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.ikea.bigdata.protos.Order)
                com.ikea.bigdata.protos.OrderProtos.OrderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.ikea.bigdata.protos.OrderProtos.internal_static_com_ikea_bigdata_protos_Order_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.ikea.bigdata.protos.OrderProtos.internal_static_com_ikea_bigdata_protos_Order_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.ikea.bigdata.protos.OrderProtos.Order.class, com.ikea.bigdata.protos.OrderProtos.Order.Builder.class);
            }

            // Construct using com.ikea.bigdata.protos.OrderProtos.Order.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                modelNumber_ = "";

                cost_ = 0;

                email_ = "";

                shippingAddress_ = "";

                mobileNumber_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.ikea.bigdata.protos.OrderProtos.internal_static_com_ikea_bigdata_protos_Order_descriptor;
            }

            @java.lang.Override
            public com.ikea.bigdata.protos.OrderProtos.Order getDefaultInstanceForType() {
                return com.ikea.bigdata.protos.OrderProtos.Order.getDefaultInstance();
            }

            @java.lang.Override
            public com.ikea.bigdata.protos.OrderProtos.Order build() {
                com.ikea.bigdata.protos.OrderProtos.Order result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.ikea.bigdata.protos.OrderProtos.Order buildPartial() {
                com.ikea.bigdata.protos.OrderProtos.Order result = new com.ikea.bigdata.protos.OrderProtos.Order(this);
                result.modelNumber_ = modelNumber_;
                result.cost_ = cost_;
                result.email_ = email_;
                result.shippingAddress_ = shippingAddress_;
                result.mobileNumber_ = mobileNumber_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.ikea.bigdata.protos.OrderProtos.Order) {
                    return mergeFrom((com.ikea.bigdata.protos.OrderProtos.Order)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.ikea.bigdata.protos.OrderProtos.Order other) {
                if (other == com.ikea.bigdata.protos.OrderProtos.Order.getDefaultInstance()) return this;
                if (!other.getModelNumber().isEmpty()) {
                    modelNumber_ = other.modelNumber_;
                    onChanged();
                }
                if (other.getCost() != 0) {
                    setCost(other.getCost());
                }
                if (!other.getEmail().isEmpty()) {
                    email_ = other.email_;
                    onChanged();
                }
                if (!other.getShippingAddress().isEmpty()) {
                    shippingAddress_ = other.shippingAddress_;
                    onChanged();
                }
                if (!other.getMobileNumber().isEmpty()) {
                    mobileNumber_ = other.mobileNumber_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.ikea.bigdata.protos.OrderProtos.Order parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.ikea.bigdata.protos.OrderProtos.Order) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object modelNumber_ = "";
            /**
             * <code>string modelNumber = 1;</code>
             */
            public java.lang.String getModelNumber() {
                java.lang.Object ref = modelNumber_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    modelNumber_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string modelNumber = 1;</code>
             */
            public com.google.protobuf.ByteString
            getModelNumberBytes() {
                java.lang.Object ref = modelNumber_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    modelNumber_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string modelNumber = 1;</code>
             */
            public Builder setModelNumber(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                modelNumber_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string modelNumber = 1;</code>
             */
            public Builder clearModelNumber() {

                modelNumber_ = getDefaultInstance().getModelNumber();
                onChanged();
                return this;
            }
            /**
             * <code>string modelNumber = 1;</code>
             */
            public Builder setModelNumberBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                modelNumber_ = value;
                onChanged();
                return this;
            }

            private int cost_ ;
            /**
             * <code>int32 cost = 2;</code>
             */
            public int getCost() {
                return cost_;
            }
            /**
             * <code>int32 cost = 2;</code>
             */
            public Builder setCost(int value) {

                cost_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 cost = 2;</code>
             */
            public Builder clearCost() {

                cost_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object email_ = "";
            /**
             * <code>string email = 3;</code>
             */
            public java.lang.String getEmail() {
                java.lang.Object ref = email_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    email_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string email = 3;</code>
             */
            public com.google.protobuf.ByteString
            getEmailBytes() {
                java.lang.Object ref = email_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    email_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string email = 3;</code>
             */
            public Builder setEmail(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                email_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string email = 3;</code>
             */
            public Builder clearEmail() {

                email_ = getDefaultInstance().getEmail();
                onChanged();
                return this;
            }
            /**
             * <code>string email = 3;</code>
             */
            public Builder setEmailBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                email_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object shippingAddress_ = "";
            /**
             * <code>string shippingAddress = 4;</code>
             */
            public java.lang.String getShippingAddress() {
                java.lang.Object ref = shippingAddress_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    shippingAddress_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string shippingAddress = 4;</code>
             */
            public com.google.protobuf.ByteString
            getShippingAddressBytes() {
                java.lang.Object ref = shippingAddress_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    shippingAddress_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string shippingAddress = 4;</code>
             */
            public Builder setShippingAddress(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                shippingAddress_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string shippingAddress = 4;</code>
             */
            public Builder clearShippingAddress() {

                shippingAddress_ = getDefaultInstance().getShippingAddress();
                onChanged();
                return this;
            }
            /**
             * <code>string shippingAddress = 4;</code>
             */
            public Builder setShippingAddressBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                shippingAddress_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object mobileNumber_ = "";
            /**
             * <code>string mobileNumber = 5;</code>
             */
            public java.lang.String getMobileNumber() {
                java.lang.Object ref = mobileNumber_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    mobileNumber_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string mobileNumber = 5;</code>
             */
            public com.google.protobuf.ByteString
            getMobileNumberBytes() {
                java.lang.Object ref = mobileNumber_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    mobileNumber_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string mobileNumber = 5;</code>
             */
            public Builder setMobileNumber(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                mobileNumber_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string mobileNumber = 5;</code>
             */
            public Builder clearMobileNumber() {

                mobileNumber_ = getDefaultInstance().getMobileNumber();
                onChanged();
                return this;
            }
            /**
             * <code>string mobileNumber = 5;</code>
             */
            public Builder setMobileNumberBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                mobileNumber_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.ikea.bigdata.protos.Order)
        }

        // @@protoc_insertion_point(class_scope:com.ikea.bigdata.protos.Order)
        private static final com.ikea.bigdata.protos.OrderProtos.Order DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.ikea.bigdata.protos.OrderProtos.Order();
        }

        public static com.ikea.bigdata.protos.OrderProtos.Order getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Order>
                PARSER = new com.google.protobuf.AbstractParser<Order>() {
            @java.lang.Override
            public Order parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Order(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Order> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Order> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.ikea.bigdata.protos.OrderProtos.Order getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_ikea_bigdata_protos_Order_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_ikea_bigdata_protos_Order_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\010my.proto\022\027com.ikea.bigdata.protos\"h\n\005O" +
                        "rder\022\023\n\013modelNumber\030\001 \001(\t\022\014\n\004cost\030\002 \001(\005\022" +
                        "\r\n\005email\030\003 \001(\t\022\027\n\017shippingAddress\030\004 \001(\t\022" +
                        "\024\n\014mobileNumber\030\005 \001(\tB&\n\027com.ikea.bigdat" +
                        "a.protosB\013OrderProtosb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_com_ikea_bigdata_protos_Order_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_ikea_bigdata_protos_Order_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_ikea_bigdata_protos_Order_descriptor,
                new java.lang.String[] { "ModelNumber", "Cost", "Email", "ShippingAddress", "MobileNumber", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
